### ISSUE TITLE
Link to the manual page in README.md outdated

### ISSUE THREAD

**Issue by SharkWipf** [Adyen/adyen-magento-subscription#100]
The link for the manual page in README.md (https://docs.adyen.com/display/TD/Magento+Subscriptions) no longer resolves to the documentation of this plugin and instead resolves to https://docs.adyen.com/developers.

**Comment by rikterbeek** [comment]
Hi @SharkWipf,

Thanks for letting us know. This is now fixed.

Regards,
Rik
Adyen
