### ISSUE TITLE
Day parameter setting

### ISSUE THREAD

**Issue by lfluvisotto** [Adyen/adyen-magento-subscription#104]
https://github.com/Adyen/adyen-magento-subscription/blob/742d37615b79673e01c74badb02d0dd72be4e2f3/app/code/community/Adyen/Subscription/Model/Cron.php#L59

I had some incidents with the method of payment sepa and multibanco where authorization returned 3 days later.

In these cases the signature was not created I had to create manually via shell / adyen_subscription.php

What do you all think of us parameterizing this D-1 with other options like D-3, D-5, D-7?

**Comment by rikterbeek** [comment]
Hi @lfluvisotto,

multibanco is not a payment method that support recurring, indeed for sepa it can take a couple of days to retrieve the money. I think 1 day is a bit to short we could extend it to 5 days so we don't miss any orders, @sandermangel does that work for you as well ?

Regards,
Rik
Adyen

**Comment by lfluvisotto** [comment]
@sandermangel

**Comment by sandermangel** [comment]
@lfluvisotto  @rikterbeek  sorry guys, missed this one. If you don't mind I'll run a couple of tests on our live data first to see what we miss. I'll schedule time early next week

**Comment by sandermangel** [comment]
@lfluvisotto @rikterbeek I see we already created a local fix for this 

`$collection->addFieldToFilter('main_table.created_at', array('lteq' => date('Y-m-d H:i:s', strtotime('-15 minutes'))));`
`$collection->addFieldToFilter('main_table.created_at', array('gteq' => date('Y-m-d H:i:s', strtotime('-30 days'))));`

The upper limit of 15 minutes is to prevent creating a subscription on an order that will be changed by an admin user. We had an issue where the customer service made a mistake and cancelled the order frequently leaving a lot of orphaned data
