### ISSUE TITLE
No subscription, product is added multiple times instead of combining and higher the quantity

### ISSUE THREAD

**Issue by rikterbeek** [Adyen/adyen-magento-subscription#2]
Product Item is added multiple times in cart if you do not choose for a subscription this should be combined
![screen shot 2015-07-29 at 9 37 00 am](https://cloud.githubusercontent.com/assets/5948499/8952238/96b9165c-35d5-11e5-8381-49a5d006ed2c.png)

**Comment by Maikel-Koek** [comment]
This is fixed in a4a479223b6ecdd97a119d5325a65edb74fa6efd, closing issue.
