### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by paales** [Adyen/adyen-magento-subscription#29]
- [ ] Getting started: Requirements + Installation
- [ ] Settings

- [ ] Faq
- [ ] Admin Pages
- [ ] Frontend intergration

**Comment by peter-fitforme** [comment]
Please add:

Contact Adyen to update Merchant Account settings:
RECURRING_CONTRACT notification must be enabled

**Comment by rikterbeek** [comment]
This is already included in our manual see: https://docs.adyen.com/display/TD/Magento+Subscriptions+Requirements
