### ISSUE TITLE
Sales order grid not updated for orders from subscription

### ISSUE THREAD

**Issue by sandermangel** [Adyen/adyen-magento-subscription#44]
When an order is created from a subscription data is missing from the sales order grid. It's only added after opening the order. Values like `customer id` and `subscription id` are left blank.

Since it's probably caused by some events e.d. not being triggered other stuff might also not get applied to these orders.

**Comment by rikterbeek** [comment]
Hi Sander,

I see in the database that the values are set. subscription_id in the sales_flat_order_grid is as well set.
So where is that data not saved on your end ?

Regards,
Rik
Adyen

**Comment by sandermangel** [comment]
It's in `sales_flat_order_grid`. The bug only happens with orders from subscriptions

**Comment by rikterbeek** [comment]
Hi Sander,

I could not reproduce this. In my case the values are set.

Regards,
Rik
Adyen
