### ISSUE TITLE
Subscription pricing with configurable products

### ISSUE THREAD

**Issue by PixelGarden** [Adyen/adyen-magento-subscription#51]
When using configurable products combined with Adyen subscriptions the pricing set in the "Super product attributes configuration" isn't translated to product once ordered.

Example:

**Product X has two variations:**
Product X (variation A) - price €15
Product X (variation B) - price €20 (BASE/FIXED + €5)

So if a customer would order variation B the subscription price should be +€5, but unfortunately that doesn't seem to work. If a customer orders the €20 product, the price will be €15 once it is added to the cart.

Therefore it seems it's impossible to use Adyen Subscription together with Magento's configurable products once the variations have different prices.

**Comment by rikterbeek** [comment]
Hi,

I understand your problem. I am looking it into if we can make support for this.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi PixelGarden,

See the changes in the commit above. I think this will solve your issues.

Regards,
Rik
Adyen
