### ISSUE TITLE
1 cent is added to the order as subscription fee

### ISSUE THREAD

**Issue by mdlonline** [Adyen/adyen-magento-subscription#53]
For every order placed with SEPA or iDeal payment there is 1 cent added. 

We do not want this to happen, as we pay the subscription fee and not the customer. If there is a subscription price of 21,50 the customer should pay 21,50 and not 21,51

There also is no option to disable this

**Comment by rikterbeek** [comment]
Hi mdlonline,

This should only happen when the amount is zero. What version of our module do you use ?
Here you can see that there is a check if the grandTotal is zero:
https://github.com/Adyen/adyen-magento-subscription/blob/develop/app/code/community/Adyen/Subscription/Model/Sales/Quote/Address/Total/SubscriptionFee.php#L45-L58


Regards,
Rik
Adyen

**Comment by mdlonline** [comment]
Hi Rik

We are using the latest version, updated it this morning for this reason. Seems the check does not work.

**Comment by rikterbeek** [comment]
Hi mdlonline,

Can you debug what the value of the grandTotal is ?
Do you have other modules that are working with totals ? If these are not correctly configured it could conflict with our totals definition.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @mdlonline,

Is this solved ?

Regards,
Rik
Adyen

**Comment by mdlonline** [comment]
Hi rik

Sorry for not replying, yes this is solved.
As far as I can remember we did a update of the extension and it worked.

Regards

Mike

**Comment by rikterbeek** [comment]
Hi @mdlonline,

Great, closing this issue then.

Regards,
Rik
Adyen
