### ISSUE TITLE
An error occurred while adding a product to the quote:

### ISSUE THREAD

**Issue by cesaroito** [Adyen/adyen-magento-subscription#57]
After my customer buys a product that uses the Adyen subscription, it would have to be charged 30 days later. But he is being charged in 15 days and beyond that displays the following error message: "An error occurred while adding a product to the quote:" Another issue is that when I try to edit the subscription on the admin, show me the same error. I just can pause or cancel the subscription . The problem is that the subscription must be collected within 30 days and is giving this error which is in Loop.

I send to you the log of Adyen subscription exception.

```
2016-05-19T15:40:05+00:00 ERR (3): 
exception 'Adyen_Subscription_Exception' with message 'An error occurred while adding a product to the quote: ' in /home/petite/public_html/app/code/community/Adyen/Subscription/Exception.php:38
Stack trace:
#0 /home/petite/public_html/app/code/community/Adyen/Subscription/Model/Service/Subscription.php(76): Adyen_Subscription_Exception::throwException('An error occurr...')
#1 /home/petite/public_html/app/code/community/Adyen/Subscription/Model/Cron.php(135): Adyen_Subscription_Model_Service_Subscription->createQuote(Object(Adyen_Subscription_Model_Subscription))
#2 [internal function]: Adyen_Subscription_Model_Cron->createQuotes(Object(Aoe_Scheduler_Model_Schedule))
#3 /home/petite/public_html/app/code/community/Aoe/Scheduler/Model/Observer.php(79): call_user_func_array(Array, Array)
#4 /home/petite/public_html/app/code/core/Mage/Core/Model/App.php(1357): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#5 /home/petite/public_html/app/code/core/Mage/Core/Model/App.php(1336): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#6 /home/petite/public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#7 /home/petite/public_html/cron.php(77): Mage::dispatchEvent('default')
#8 {main}
```

How to fix that?

Best,

**Comment by rikterbeek** [comment]
Hi @cesaroito,

What version of our module are you using ? I think this will solve your issue: https://github.com/Adyen/adyen-magento-subscription/pull/50
Should be included in our latest version.

Regards,
Rik
Adyen

**Comment by cesaroito** [comment]
Hi Rik,

I create a simple product at the same store and works fine to edit subscription and schedule an order. The problem it's with configurable product.
I use Adyen Subscription module in more than one stores and the same problem it's only with configurable product.
I use the last version of Adyen Subscription (1.1.1).

**Comment by rikterbeek** [comment]
Hi Ceasar,

I maded a fix for configurable products here and should be in the 1.1.1 release see https://github.com/Adyen/adyen-magento-subscription/commit/04daf9bbca91f3f43d89682f865068974c61768c

Could you debug on the points that where change if you can get it working ?

Can you share me your configurable product configurations so I can reproduce the issue ?
If you don't want to share this in public please contact us at magento@adyen.com.


Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Ceasar,

Check out this fix as well (not in release version yet) https://github.com/Adyen/adyen-magento-subscription/commit/384b883c08cf9479923530beac2248344cdcdcfb

Regards,
Rik
Adyen

**Comment by cesaroito** [comment]
Hi Rik,

It works fine!!! Thanks for help me with that.
I send to you an email about configurable products.

Best,
