### ISSUE TITLE
Order every 30 minutes

### ISSUE THREAD

**Issue by cesaroito** [Adyen/adyen-magento-subscription#63]
Hello,

I have an issue.
<img width="1280" alt="screen shot 2016-06-07 at 11 21 40" src="https://cloud.githubusercontent.com/assets/7848165/15861659/57fb0d92-2ca3-11e6-9ed0-8f8b4525ec2c.png">

In my magento store, I config Time (in hours) between retries payment failure every 72 hours and 3 times Number of retries for payment failure. The problem it's not work because this retry happens every 30 minutes in Adyen dashboard. I send to you an image about that.

Regards,

**Comment by rikterbeek** [comment]
Hi @cesaroito,

What is the status of the subscription ?
Are you able to debug ? here is the code where this is checked:
https://github.com/Adyen/adyen-magento-subscription/blob/develop/app/code/community/Adyen/Subscription/Model/Cron.php#L188-L244

Regards,
Rik
Adyen

**Comment by cesaroito** [comment]
Hello Rik,

The status of subscription is active. I have to pause the subscription to stop to try to create an order every 30 minutes. This is happening when the first try is fail.
Regards,

**Comment by rikterbeek** [comment]
Hi @cesaroito,

That is strange that the status is active if the payment failed this should result in a payment error.
Can you look into the logs why the status is not set to payment error ?

Regards,
Rik
Adyen

**Comment by cesaroito** [comment]
Hello Rik,

Sorry for the information. it was wrong. The correct information is: "order creation error". The message of this error can be various like: Please specify a shipping method (That is strange because of that order has a shipping method that not changed). Another messages: The payment is Refused. When I try to open this subscription in my magento store, there is an error. I send to you two images of this situation.
I send to you the logs of the last day of store.

Regards,
[adyen-08-06-2016.zip](https://github.com/Adyen/adyen-magento-subscription/files/305022/adyen-08-06-2016.zip)
<img width="1280" alt="screenshot 2016-06-08 11 45 00" src="https://cloud.githubusercontent.com/assets/7848165/15898544/224a9b6e-2d6f-11e6-9c0a-8f8bd2235485.png">
<img width="1280" alt="screenshot 2016-06-08 11 46 23" src="https://cloud.githubusercontent.com/assets/7848165/15898546/226b1cae-2d6f-11e6-9624-898bd0f2578c.png">

**Comment by rikterbeek** [comment]
Hi @cesaroito,

The reason "Please specify a shipping method" is coming from core magento. It is trying to create a quote or order but the shipping method is not available think you need to check if the shipping method is possible to use ? could you update the subscription selecting a new shipping method ?

Regards,
Rik
Adyen

**Comment by cesaroito** [comment]
Hi Rik,

The shipping method it's the same. If I edit this subscription I can use a new shipping method.

**Comment by rikterbeek** [comment]
Hi @cesaroito,

The problem is converting the quote to an order. This is done by Magento itself.
The exception is thrown here: 

https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Sales/Model/Service/Quote.php#L303

And called by us here:
https://github.com/Adyen/adyen-magento-subscription/blob/develop/app/code/community/Adyen/Subscription/Model/Service/Quote.php#L62

Could you debug if the quote has a shippingMethod set?
Shipping method on the quote should be set here: https://github.com/Adyen/adyen-magento-subscription/blob/develop/app/code/community/Adyen/Subscription/Model/Service/Subscription.php#L141-L143

Regards,
Rik

**Comment by cesaroito** [comment]
Hello Rik,

The problem with shipping method I fixed. It was because when I change something in my table rate, the shipping method change too.

Now my problem it's about the payment fail. I config to to retrie to payment failure that doesn't work. I send to you a printscreen.

Regards,
![screen shot 2016-06-20 at 08 32 22](https://cloud.githubusercontent.com/assets/7848165/16192791/ad929e3c-36c1-11e6-984c-aa195e7f69a7.png)

**Comment by rikterbeek** [comment]
Hi @cesaroito,

What status does you subscription goes to ?

Regards,
Rik
Adyen

**Comment by cesaroito** [comment]
Hi @rikterbeek,

Status of my subscription: Order creation error. You can see the subscription 139. The message is: "The payment is Refused. The date is: 06-16-2016. You can see in the history of this subscription that there isn't another try to payment after 72 hours. I send to you anothers screens.

Regards,
![screen shot 2016-06-20 at 08 48 40](https://cloud.githubusercontent.com/assets/7848165/16193226/42dd845a-36c4-11e6-9ece-0a5010ecd87b.png)
![screen shot 2016-06-20 at 08 50 07](https://cloud.githubusercontent.com/assets/7848165/16193227/42e2fc32-36c4-11e6-86a7-18c3b1fdc241.png)

**Comment by rikterbeek** [comment]
@cesaroito,

This is because it is not in a payment error but an order creation error. This will only apply for payment error. So something in your order creation is not correctly is this not because of the shipping error that you had earlier ?

Regards,
Rik
Adyen

**Comment by cesaroito** [comment]
I have to disable "Retry creating order" because of try to create order every 30 minutes. I fix shipping method of all my subscriptions. In Adyen dashboard show me two kinds of error: (error 800 and error 803). the Adyen team is trying to see why this is happening. I have to retry payment order manually.

Regards,
Cesar
rc-design
