### ISSUE TITLE
Adding quantity field to simple products when you want to create a new order

### ISSUE THREAD

**Issue by chester310590** [Adyen/adyen-magento-subscription#64]
I noticed when I create a new order and I want to add a simple product, which has a subscription, there is no any quantity field. For bundle products or configurable products the qty field is displayed. I did some debugging I see that it was removed from the layout:
```
<PRODUCT_TYPE_simple>
        <reference name="product.composite.fieldset">
           <remove name="product.composite.fieldset.qty"/>
</PRODUCT_TYPE_simple>
```

I commented the "remove" part and it works fine, I am wondering now why the qty.phtml file was removed  from the XML from simple products ?

Thx in advance

**Comment by rikterbeek** [comment]
Hi @chester310590,

Where did you not see the qty field ? Could you describe the steps you make was it in the front-end or in the backend ?

Regards,
Rik
Adyen

**Comment by chester310590** [comment]
Hi @rikterbeek 

This is the steps that I made in backend:
1. Create a new order 
2. Select a customer 
3. Select a simple product (not configurable or bundled), which has an adyen subscription and in the popup the qty field is missed. 

Thx

**Comment by rikterbeek** [comment]
Hi @chester310590,

I see what you mean. Thanks for letting us know it is possible so just let's not hide it.
See commit below that makes this possible. Next time just do a pull request so we can merge this into our code.

Regards,
Rik
Adyen
