### ISSUE TITLE
Bug with some adyen subscriptions

### ISSUE THREAD

**Issue by cesaroito** [Adyen/adyen-magento-subscription#65]
Hello Rik,

I have a strange situation. When a payment failed of some subscription, I try to edit this adyen subscription. If a customer doesn't have a billing information agreement, I don't get access this subscription anymore. Show me a strange screen (image attached).

Can you help me with that?

Regards,
![screen shot 2016-06-20 at 08 35 48](https://cloud.githubusercontent.com/assets/7848165/16192968/b4d3a212-36c2-11e6-8970-11969b9948d3.png)

**Comment by rikterbeek** [comment]
Hi @cesaroito,

There must be some exceptions in your logging with the reason or try to open the source code and see if you can find an error message there.

Regards,
Rik
Adyen

**Comment by cesaroito** [comment]
Hello Rik,

I didn't find a way to fix that error. I send to you my logs.
[Archive.zip](https://github.com/Adyen/adyen-magento-subscription/files/341727/Archive.zip)
