### ISSUE TITLE
3 requests to Adyen for payment methods when adding a product without subscription to cart

### ISSUE THREAD

**Issue by sandermangel** [Adyen/adyen-magento-subscription#67]
I added a product to cart with "No subscription" selected as an option. In the Adyen Exception log I found 3 entries. The entries were an error about wrong merchant credentials which is fine since it's a development environment but I wonder why the module

1. needs to make 3 calls and throw 3 of the same exceptions
2. makes a call to Adyen at all when adding a product without a subscription

**Comment by rikterbeek** [comment]
Hi @sandermangel,

If you have adyen HPP payment method active he does the Directory Lookup every time you loaded a page. When it has a result it will cache it but not if there is a request issue in this case because you have the wrong credentials filled in.

Regards,
Rik
Adyen

**Comment by sandermangel** [comment]
Hi @rikterbeek in that case I guess it's a 'feature'. Still feels a bit weird it's doing so many calls
