### ISSUE TITLE
Google Analytics issue

### ISSUE THREAD

**Issue by cesaroito** [Adyen/adyen-magento-subscription#69]
Hello Rik,

I have an issue. When a customer has a subscription, Google analytics works fine with first order. When it make a second order for this customer, Google analytics not get this orders. How to track this orders?

Best,

**Comment by rikterbeek** [comment]
Hi @cesaroito,

I think your Google tracking script is only working if the customer comes to the success page.
The second order is dynamically created so will not come to any template files because it is generated by a cron script. So I have no idea how you could do it.

Regards,
Rik
Adyen

**Comment by sandermangel** [comment]
@cesaroito you could add it via the official PHP library for Google Analytics (https://developers.google.com/analytics/devguides/reporting/core/v3/quickstart/service-php)
