### ISSUE TITLE
Shipping Rates

### ISSUE THREAD

**Issue by cesaroito** [Adyen/adyen-magento-subscription#84]
Hello,

When my customer has a subscription, the first order it's ok, but when the scheduled order for the the next month, the shipping rate it's not load. I have to edit every subscription to add the shipping.
I use "Matrix rate Module". Can you help me with that?

Regards,

**Comment by sandermangel** [comment]
Hi @cesaroito, we have the same issue. Will work on that today

**Comment by sandermangel** [comment]
@cesaroito for us it ended up to be issues with imported subscriptions, mainly missing data in the buy request. Under "product" I can see there aren't any labels filled, just an empty `:`. My guess is you have the same issue where this descriptions buy request is missing data.

On another note; might I suggest reuploading the screenshop with the name, phone number and billing agreement details blurred out?

**Comment by cesaroito** [comment]
Hello @sandermangel . After worked in this issue, did you fix it?

Thanks for advise about the screenshop.

**Comment by sandermangel** [comment]
@cesaroito it turned out to be an issue with the product data. When you edit the subscriptions, can you re-add the products and check if the proper subscription option is selected etc?

**Comment by cesaroito** [comment]
When I edit the subscriptions, I can add the products and make the right selection. What I have to do it's to edit again for choose the shipping. The problem it's about 1000 subscriptions and make this manually.

**Comment by sandermangel** [comment]
@cesaroito did you do any import or remove subscription options or something that might invalidate the data for this to happen?

**Comment by cesaroito** [comment]
No. I did not.

**Comment by sandermangel** [comment]
@cesaroito in that case I'm out of idea's. Sorry I couldn't help you, I'm sure someone from Adyen will also look into this :)

**Comment by cesaroito** [comment]
Hello @rikterbeek, any news about this issue? I didn't find any solution for that.

Regards,

**Comment by cesaroito** [comment]
Any ideas about this issue? I don't find a solution for that? I'm using the last version of Adyen Payments and Adyen Subscription.

**Comment by rikterbeek** [comment]
Hi @cesaroito,

Looks something specific to this module is this now solved ? If you could provide us with the module and how to configure this in a test solution we could check if we can reproduce it. I removed the screenshot  because of private data.

Regards,
Rik
Adyen
