### ISSUE TITLE
Mass Actions

### ISSUE THREAD

**Issue by cesaroito** [Adyen/adyen-magento-subscription#87]
Hello,

I have a question: Is that possible to make a mass action to schedule many subscriptions at the same date?

**Comment by cesaroito** [comment]
Anyone has an idea about this?

**Comment by rikterbeek** [comment]
Hi @cesaroito,

At the moment the scheduled date is determined by the subscription that the customer has chosen. This 
is calculated from the moment the product is processed. If you want the next schedule date to be the same across multiple orders you need to change the scheduled date of the orders that you want to combine to the same date.

Regards,
Rik
Adyen
