### ISSUE TITLE
Can't create new Billing agreements via subscription module

### ISSUE THREAD

**Issue by sandermangel** [Adyen/adyen-magento-subscription#90]
Issues with creating new billing agreements, and existing ones
- adyen test merchant & live merchant accounts
- adyen/adyen-magento _2.8.1_
- adyen/adyen-magento-subscription _dev-develop_ (since master forces you to use 2.5.* which caused bugs)
- Magento EE 1.14.3

**Reproduce for new BA:**
- Go to existing active subscription
  -> Schedule order
  -> Go to "scheduled order"
  -> Edit scheduled order
  -> Add new creditcard

> Name: Sander
> Credit card type: visa
> Card number: 4111111111111111
> Expiration date: 08-2018
> Card verification: 737

When submitting, I get the following error

```
Fatal error: Uncaught TypeError: Argument 2 passed to Adyen_Subscription_Model_Service_Quote::updateQuotePayment() 
must be an instance of Adyen_Payment_Model_Billing_Agreement, null given, called in 
app/code/community/Adyen/Subscription/controllers/Adminhtml/SubscriptionController.php on line 481 and defined in app/code/local/Adyen/Subscription/Model/Service/Quote.php:398 
Stack trace: #0 app/code/community/Adyen/Subscription/controllers/Adminhtml/SubscriptionController.php(481): Adyen_Subscription_Model_Service_Quote->updateQuotePayment(Object(Mage_Sales_Model_Quote), NULL, Array) 
#1 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Adyen_Subscription_Adminhtml_SubscriptionController->updateQuoteAction() 
#2 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('updateQuote') 
#3 app/code/core/Mage/Core/Controller/V in app/code/local/Adyen/Subscription/Model/Service/Quote.php on line 398
```

**Existing BA issues**
Probably related but haven't been able to reproduce locally:
- some live subscriptions scheduled for a date go to "Payment Error" status on it's scheduled date.
- click to edit, select any existing BA, submit subscription
- Error: "Payment method refused"

**Comment by rikterbeek** [comment]
Hi @sandermangel,

Does this problem still exists ?

Regards,
Rik
Adyen

**Comment by sandermangel** [comment]
@rikterbeek I think we fixed it eventually in our own version of the module, I'll close the issue

**Comment by sandermangel** [comment]
Creating new billing agreements without placing an order is still a feature we would like to have tho
