### ISSUE TITLE
Dependent module with outdated version

### ISSUE THREAD

**Issue by sabrinabandaree** [Adyen/adyen-magento-subscription#91]
Hello good afternoon

According to the images, the installation process of the "adyen/subscription" module is downloading an outdated version of the module "adyen/payment"

![captura de tela de 2017-03-17 17-27-55](https://cloud.githubusercontent.com/assets/26491932/24061677/1e2ab428-0b37-11e7-962d-7fd37ac31b8e.png)

**Comment by sandermangel** [comment]
Hi Sabrina, I have the same issue so we're currently running the develop branch in our shop.
it seems to be stable, has been working for a few months. But indeed, it should be fixed

**Comment by sabrinabandaree** [comment]
Hello good Morning

See in the image that I tried also use of the branch "dev-master"

Even so, the lagged version is downloaded

**Comment by rikterbeek** [comment]
Hi @sabrinabandaree @sandermangel,

Just did a new release and this dependency is now updated to the latest release of the payment extensoin.

Regards,
Rik
Adyen
